stages:
  - build
  - deploy

build-job:
  tags:
    # Use your group tag (e.g., green8) instead
    # of runner cs350
    - runner350
  stage: build
  script:
    - chmod a+x gradlew
    - ./gradlew --no-daemon build javadoc
  only:
    - master
  artifacts:
    # Make entire build directory available
    # for the deploy portion of the job
    paths:
      - ./build

deploy-job:
  tags:
    - runner350
  stage: deploy
  script:
    #- eval $(ssh-agent -s)
    #- ssh-add <(echo "$RSYNC_KEY")
    #- rsync -auvz -e "ssh" build/directoriesToCopy yourLoginName@atria.cs.odu.edu:GitLab1/
    #
    # Kill the ssh-agent process
    #- ssh-agent -k
    # Print available items (for debugging)
    - echo "--------RSYNC PLACEHOLDER--------"    
    - ls -lah
    - echo "------------------------"
    - ls -lah build
    - echo "------------------------"
    - ls -lah build/reports
    - echo "------------------------"
    - ls -lah build/docs